# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='undergrad',
            new_name='population',
        ),
    ]
