# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20160206_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='checktest',
            field=models.BooleanField(default=True),
        ),
    ]
