# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_auto_20160206_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='aboutpolicies',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='aboutpoliciesonline',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='aboutreporting',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='aboutreportingonline',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='allreports',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='climatestudy',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='consent',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='datingviolence',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='domesticviolence',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='facultystafftraining',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='mensgroup',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='oncampusreports',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='otheroffices',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='primaryprevention',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='riskreduction',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='sexualassault',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='sexualharassment',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='stalking',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='studentinitiative',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='titleixoffice',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='volunteergroup',
            field=models.NullBooleanField(default=False),
        ),
    ]
