# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20160206_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('logo', models.CharField(default='', max_length=300)),
                ('coordinator', models.CharField(default='', max_length=100)),
                ('coordinator_email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
